name: Build iOS App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods
        pod --version
    
    - name: Install dependencies
      working-directory: ./ios
      run: |
        pod install --repo-update
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: List available schemes
      working-directory: ./ios
      run: |
        xcodebuild -workspace SecretChelSociety.xcworkspace -list
    
    - name: Build for iOS Simulator
      working-directory: ./ios
      run: |
        xcodebuild -workspace SecretChelSociety.xcworkspace \
                   -scheme SecretChelSociety \
                   -destination 'platform=iOS Simulator,name=iPhone 15' \
                   -configuration Debug \
                   CODE_SIGNING_ALLOWED=NO \
                   build
    
    - name: Build for iOS Device (Archive)
      working-directory: ./ios
      run: |
        xcodebuild -workspace SecretChelSociety.xcworkspace \
                   -scheme SecretChelSociety \
                   -configuration Release \
                   -archivePath SecretChelSociety.xcarchive \
                   CODE_SIGNING_ALLOWED=NO \
                   archive
      continue-on-error: true
